#!/usr/bin/python

import sys, difflib, optparse
from openpyxl import Workbook

def main():
    usage = "usage: %prog fromfile tofile output.xlsx"

    parser = optparse.OptionParser(usage)
    parser.add_option("-l", "--lines", type="int", default=2,
                      help='Set number of context lines (default 2)')
    (options, args) = parser.parse_args()

    if len(args) == 0:
        parser.print_help()
        sys.exit(1)
    if len(args) != 3:
        parser.error("need to specify both a fromfile, tofile, and output.xlsx")

    n = options.lines
    fromfile, tofile, outfile = args

    fromlines = open(fromfile, 'U').readlines()
    tolines = open(tofile, 'U').readlines()

    sm = difflib.SequenceMatcher(None, fromlines, tolines)
    all_ops = sm.get_grouped_opcodes(n)

    wb = Workbook()
    ws = wb.active
    row = 1
    for group in all_ops:
        (i, j, k, l) = (0, 0, 0, 0)
        for ops in group:
            (op, tmp_i, tmp_j, tmp_k, tmp_l) = ops
            if i == 0:
                i = tmp_i
            j = tmp_j
            if k == 0:
                k = tmp_k
            l = tmp_l
        cell = ws.cell(row=row, column=1)
        cell.value = str.join('', fromlines[i:j])
        cell = ws.cell(row=row, column=2)
        cell.value = str.join('', tolines[k:l])
        row += 1
    wb.save(outfile)

if __name__ == '__main__':
    main()
